/**
 * @file scadtemplates.hpp
 * @brief Main header file for the scadtemplates library
 * 
 * This is the main include file for the scadtemplates library.
 * Include this file to access all library functionality.
 * 
 * **Version and Application Metadata:**
 * - Application name, version, and build information are auto-generated by CMake
 * - Single source of truth: AppInfo.cmake (editable) → CMakeLists.txt (processing) → applicationNameInfo.hpp (generated)
 * - Access via: appInfo::displayName, appInfo::version, appInfo::versionMajor, appInfo::author, appInfo::organization
 * - See applicationNameInfo.hpp for all available metadata constants
 * 
 * @author Jeff Hayes
 * @copyright MIT License
 * 
 * @section usage Usage
 * 
 * @code{.cpp}
 * #include <scadtemplates/scadtemplates.hpp>
 * #include <iostream>
 * 
 * int main() {
 *     scadtemplates::SnippetManager manager;
 *     
 *     // Create and add a template
 *     scadtemplates::Template tmpl("cube", "cube([$1, $2, $3]);", "Create a cube");
 *     manager.addTemplate(tmpl);
 *     
 *     // Find a template
 *     auto found = manager.findByPrefix("cube");
 *     if (found) {
 *         std::cout << found->getBody() << std::endl;
 *     }
 *     
 *     return 0;
 * }
 * @endcode
 * 
 * @section metadata Application Metadata
 * 
 * For application name, version, and build information:
 * @code{.cpp}
 * #include "applicationNameInfo.hpp"
 * 
 * std::cout << appInfo::displayName << " v" << appInfo::version << std::endl;
 * // Output: "ScadTemplates v2.43.0" (or "ScadTemplates (Nightly) v2.43.0" if APP_SUFFIX is set)
 * 
 * std::cout << "Git commit: " << appInfo::gitCommitHash << std::endl;
 * std::cout << "Author: " << appInfo::author << std::endl;
 * @endcode
 * 
 * @section building Building
 * 
 * The library can be built using CMake:
 * @code{.sh}
 * mkdir build && cd build
 * cmake ..
 * cmake --build . --config Debug --parallel 4
 * @endcode
 * 
 * Build options:
 * - BUILD_SHARED_LIBS: Build as shared library (default: ON)
 * - BUILD_TESTS: Build test suite (default: OFF)
 * - BUILD_APP: Build Qt application (default: ON)
 * 
 * Build with custom app name and suffix:
 * @code{.sh}
 * cmake -DAPP_NAME="MyApp" -DAPP_SUFFIX="Nightly" -G Ninja -S . -B build
 * @endcode
 */

#pragma once

#include "export.hpp"
#include "template.hpp"
#include "template_parser.hpp"
#include "template_manager.hpp"

/**
 * @namespace scadtemplates
 * @brief Main namespace for the scadtemplates library
 */
namespace scadtemplates {

// Version information has been consolidated into applicationNameInfo.hpp
// For version info, use: appInfo::version, appInfo::versionMajor, etc.

} // namespace scadtemplates
